import { registerNamespace } from "../register"

// IMPORTANT NOTE: The automatically assigned value to each of the enums is completely meaningless (and never visible to any code)
// The exported object from this file is generated by registerNamespace() from the namespace definition.
// All enums values are converted into strings for use in Vuex's commit() and dispatch() functions.

namespace Auth {
  export enum Getters {}

  export enum Actions {
    WaitForLogin,
    LoginComplete,
    LoadUser,
    ClearUser,
  }

  export enum Mutations {
    SetLoginFormVisibility,
  }

  export enum Events {}
}

export default registerNamespace("Auth", Auth)
